### ISSUE TITLE
Why isn't Statsboxd working anymore?

### ISSUE THREAD

**Issue by DGnie** [GiuDiMax/statsboxd-svelte#1]
The page says I've been blocked but I didn't do anything.

**Comment by GiuDiMax** [comment]
Old.statsboxd.top is now only for supporters
Statsboxd.top (with file upload) is open to all

**Comment by DGnie** [comment]
Oh, thanks for info. But I'm not sure where I'm supposed to upload Letterboxd data in the second one though.
